
create schema api;
alter schema api owner to latexinarxiv;
create role web_anon nologin;
grant usage on schema api to web_anon;
create role authenticator noinherit login password 'mysecretpassword';
grant web_anon to authenticator;

create table api.abstract (index int,abstract text,filename text,checksum text);
create table api.acknowledgments (index int,acknowledgments text,filename text,checksum text);
create table api.affiliation (index int,affiliation text,filename text,checksum text);
create table api.align (index int,align text,filename text,checksum text);
create table api.alignat (index int,alignat text,filename text,checksum text);
create table api.aligned (index int,aligned text,filename text,checksum text);
create table api.author (index int,author text,filename text,checksum text);
create table api.cases (index int,cases text,filename text,checksum text);
create table api.center (index int,center text,filename text,checksum text);
create table api.cite (index int,cite text,filename text,checksum text);
create table api.definition (index int,definition text,filename text,checksum text);
create table api.description (index int,description text,filename text,checksum text);
create table api.displaymath (index int,displaymath text,filename text,checksum text);
create table api.document (index int,document text,filename text,checksum text);
create table api.enumerate (index int,enumerate text,filename text,checksum text);
create table api.eq (index int,eq text,filename text,checksum text);
create table api.eqnarray (index int,eqnarray text,filename text,checksum text);
create table api.equation (index int,equation text,filename text,checksum text);
create table api.figure (index int,figure text,filename text,checksum text);
create table api.flushleft (index int,flushleft text,filename text,checksum text);
create table api.flushright (index int,flushright text,filename text,checksum text);
create table api.fractions (index int,fractions text,filename text,checksum text);
create table api.gather (index int,gather text,filename text,checksum text);
create table api.itemize (index int,itemize text,filename text,checksum text);
create table api.label (index int,label text,filename text,checksum text);
create table api.matrix (index int,matrix text,filename text,checksum text);
create table api.minipage (index int,minipage text,filename text,checksum text);
create table api.multline (index int,multline text,filename text,checksum text);
create table api.pacs (index int,pacs text,filename text,checksum text);
create table api.picture (index int,picture text,filename text,checksum text);
create table api.pmatrix (index int,pmatrix text,filename text,checksum text);
create table api.proof (index int,proof text,filename text,checksum text);
create table api.prop (index int,prop text,filename text,checksum text);
create table api.quote (index int,quote text,filename text,checksum text);
create table api.ref (index int,ref text,filename text,checksum text);
create table api.section (index int,section text,filename text,checksum text);
create table api.small (index int,small text,filename text,checksum text);
create table api.split (index int,split text,filename text,checksum text);
create table api.subequations (index int,subequations text,filename text,checksum text);
create table api.tabular (index int,tabular text,filename text,checksum text);
create table api.thebibliography (index int,thebibliography text,filename text,checksum text);
create table api.theorem (index int,theorem text,filename text,checksum text);
create table api.thm (index int,thm text,filename text,checksum text);
create table api.title (index int,title text,filename text,checksum text);
create table api.titlepage (index int,titlepage text,filename text,checksum text);
create table api.twomatrix (index int,twomatrix text,filename text,checksum text);
create table api.usepackage (index int,usepackage text,filename text,checksum text);
create table api.widetext (index int,widetext text,filename text,checksum text);


alter table api.abstract owner to latexinarxiv;
alter table api.acknowledgments owner to latexinarxiv;
alter table api.affiliation owner to latexinarxiv;
alter table api.align owner to latexinarxiv;
alter table api.alignat owner to latexinarxiv;
alter table api.aligned owner to latexinarxiv;
alter table api.author owner to latexinarxiv;
alter table api.cases owner to latexinarxiv;
alter table api.center owner to latexinarxiv;
alter table api.cite owner to latexinarxiv;
alter table api.definition owner to latexinarxiv;
alter table api.description owner to latexinarxiv;
alter table api.displaymath owner to latexinarxiv;
alter table api.document owner to latexinarxiv;
alter table api.enumerate owner to latexinarxiv;
alter table api.eq owner to latexinarxiv;
alter table api.eqnarray owner to latexinarxiv;
alter table api.equation owner to latexinarxiv;
alter table api.figure owner to latexinarxiv;
alter table api.flushleft owner to latexinarxiv;
alter table api.flushright owner to latexinarxiv;
alter table api.fractions owner to latexinarxiv;
alter table api.gather owner to latexinarxiv;
alter table api.itemize owner to latexinarxiv;
alter table api.label owner to latexinarxiv;
alter table api.matrix owner to latexinarxiv;
alter table api.minipage owner to latexinarxiv;
alter table api.multline owner to latexinarxiv;
alter table api.pacs owner to latexinarxiv;
alter table api.picture owner to latexinarxiv;
alter table api.pmatrix owner to latexinarxiv;
alter table api.proof owner to latexinarxiv;
alter table api.prop owner to latexinarxiv;
alter table api.quote owner to latexinarxiv;
alter table api.ref owner to latexinarxiv;
alter table api.section owner to latexinarxiv;
alter table api.small owner to latexinarxiv;
alter table api.split owner to latexinarxiv;
alter table api.subequations owner to latexinarxiv;
alter table api.tabular owner to latexinarxiv;
alter table api.thebibliography owner to latexinarxiv;
alter table api.theorem owner to latexinarxiv;
alter table api.thm owner to latexinarxiv;
alter table api.title owner to latexinarxiv;
alter table api.titlepage owner to latexinarxiv;
alter table api.twomatrix owner to latexinarxiv;
alter table api.usepackage owner to latexinarxiv;
alter table api.widetext owner to latexinarxiv;


grant select on api.abstract to web_anon;
grant select on api.acknowledgments to web_anon;
grant select on api.affiliation to web_anon;
grant select on api.align to web_anon;
grant select on api.alignat to web_anon;
grant select on api.aligned to web_anon;
grant select on api.author to web_anon;
grant select on api.cases to web_anon;
grant select on api.center to web_anon;
grant select on api.cite to web_anon;
grant select on api.definition to web_anon;
grant select on api.description to web_anon;
grant select on api.displaymath to web_anon;
grant select on api.document to web_anon;
grant select on api.enumerate to web_anon;
grant select on api.eq to web_anon;
grant select on api.eqnarray to web_anon;
grant select on api.equation to web_anon;
grant select on api.figure to web_anon;
grant select on api.flushleft to web_anon;
grant select on api.flushright to web_anon;
grant select on api.fractions to web_anon;
grant select on api.gather to web_anon;
grant select on api.itemize to web_anon;
grant select on api.label to web_anon;
grant select on api.matrix to web_anon;
grant select on api.minipage to web_anon;
grant select on api.multline to web_anon;
grant select on api.pacs to web_anon;
grant select on api.picture to web_anon;
grant select on api.pmatrix to web_anon;
grant select on api.proof to web_anon;
grant select on api.prop to web_anon;
grant select on api.quote to web_anon;
grant select on api.ref to web_anon;
grant select on api.section to web_anon;
grant select on api.small to web_anon;
grant select on api.split to web_anon;
grant select on api.subequations to web_anon;
grant select on api.tabular to web_anon;
grant select on api.thebibliography to web_anon;
grant select on api.theorem to web_anon;
grant select on api.thm to web_anon;
grant select on api.title to web_anon;
grant select on api.titlepage to web_anon;
grant select on api.twomatrix to web_anon;
grant select on api.usepackage to web_anon;
grant select on api.widetext to web_anon;
