
/* A lexical scanner generated by flex */

/* Target: C/C++ */
/* START of m4 controls */
/* M4_YY_TABLES_VERIFY = 0 */
/* YY_MAIN = 0 */
/* M4_MODE_NO_DO_STDINIT */
/* M4_MODE_NO_YYTEXT_IS_ARRAY */
/* M4_MODE_NO_YYMORE_USED */
/* M4_MODE_REAL_FULLSPD */
/* M4_MODE_NO_REAL_FULLTBL */
/* M4_MODE_NO_CPP_USE_READ */
/* M4_MODE_NO_VARIABLE_TRAILING_CONTEXT_RULES */
/* M4_MODE_FIND_ACTION_REJECT_REALLY_USED */
/* M4_MODE_NO_USES_REJECT */
/* M4_MODE_FULLSPD */
/* M4_MODE_NO_BOL_NEEDED */
/* M4_MODE_NO_USEECS */
/* M4_MODE_GENTABLES */
/* M4_MODE_NO_INTERACTIVE */
/* M4_MODE_NO_YYWRAP */
/* M4_MODE_C_ONLY */
/* M4_MODE_PREFIX = S1_ */
/* M4_MODE_NO_YYINPUT */
/* M4_YY_NO_TOP_STATE */
/* M4_YY_NO_YYUNPUT */
/* M4_YY_STACK_USED */
/* M4_MODE_NO_REWRITE */
/* END of m4 controls */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

#ifdef yy_create_buffer
#define S1__create_buffer_ALREADY_DEFINED
#else
#define yy_create_buffer S1__create_buffer
#endif

#ifdef yy_delete_buffer
#define S1__delete_buffer_ALREADY_DEFINED
#else
#define yy_delete_buffer S1__delete_buffer
#endif

#ifdef yy_scan_buffer
#define S1__scan_buffer_ALREADY_DEFINED
#else
#define yy_scan_buffer S1__scan_buffer
#endif

#ifdef yy_scan_string
#define S1__scan_string_ALREADY_DEFINED
#else
#define yy_scan_string S1__scan_string
#endif

#ifdef yy_scan_bytes
#define S1__scan_bytes_ALREADY_DEFINED
#else
#define yy_scan_bytes S1__scan_bytes
#endif

#ifdef yy_init_buffer
#define S1__init_buffer_ALREADY_DEFINED
#else
#define yy_init_buffer S1__init_buffer
#endif

#ifdef yy_flush_buffer
#define S1__flush_buffer_ALREADY_DEFINED
#else
#define yy_flush_buffer S1__flush_buffer
#endif

#ifdef yy_load_buffer_state
#define S1__load_buffer_state_ALREADY_DEFINED
#else
#define yy_load_buffer_state S1__load_buffer_state
#endif

#ifdef yy_switch_to_buffer
#define S1__switch_to_buffer_ALREADY_DEFINED
#else
#define yy_switch_to_buffer S1__switch_to_buffer
#endif

#ifdef yypush_buffer_state
#define S1_push_buffer_state_ALREADY_DEFINED
#else
#define yypush_buffer_state S1_push_buffer_state
#endif

#ifdef yypop_buffer_state
#define S1_pop_buffer_state_ALREADY_DEFINED
#else
#define yypop_buffer_state S1_pop_buffer_state
#endif

#ifdef yyensure_buffer_stack
#define S1_ensure_buffer_stack_ALREADY_DEFINED
#else
#define yyensure_buffer_stack S1_ensure_buffer_stack
#endif

#ifdef yylex
#define S1_lex_ALREADY_DEFINED
#else
#define yylex S1_lex
#endif

#ifdef yyrestart
#define S1_restart_ALREADY_DEFINED
#else
#define yyrestart S1_restart
#endif

#ifdef yylex_init
#define S1_lex_init_ALREADY_DEFINED
#else
#define yylex_init S1_lex_init
#endif

#ifdef yylex_init_extra
#define S1_lex_init_extra_ALREADY_DEFINED
#else
#define yylex_init_extra S1_lex_init_extra
#endif

#ifdef yylex_destroy
#define S1_lex_destroy_ALREADY_DEFINED
#else
#define yylex_destroy S1_lex_destroy
#endif

#ifdef yyget_debug
#define S1_get_debug_ALREADY_DEFINED
#else
#define yyget_debug S1_get_debug
#endif

#ifdef yyset_debug
#define S1_set_debug_ALREADY_DEFINED
#else
#define yyset_debug S1_set_debug
#endif

#ifdef yyget_extra
#define S1_get_extra_ALREADY_DEFINED
#else
#define yyget_extra S1_get_extra
#endif

#ifdef yyset_extra
#define S1_set_extra_ALREADY_DEFINED
#else
#define yyset_extra S1_set_extra
#endif

#ifdef yyget_in
#define S1_get_in_ALREADY_DEFINED
#else
#define yyget_in S1_get_in
#endif

#ifdef yyset_in
#define S1_set_in_ALREADY_DEFINED
#else
#define yyset_in S1_set_in
#endif

#ifdef yyget_out
#define S1_get_out_ALREADY_DEFINED
#else
#define yyget_out S1_get_out
#endif

#ifdef yyset_out
#define S1_set_out_ALREADY_DEFINED
#else
#define yyset_out S1_set_out
#endif

#ifdef yyget_leng
#define S1_get_leng_ALREADY_DEFINED
#else
#define yyget_leng S1_get_leng
#endif

#ifdef yyget_text
#define S1_get_text_ALREADY_DEFINED
#else
#define yyget_text S1_get_text
#endif

#ifdef yyget_lineno
#define S1_get_lineno_ALREADY_DEFINED
#else
#define yyget_lineno S1_get_lineno
#endif

#ifdef yyset_lineno
#define S1_set_lineno_ALREADY_DEFINED
#else
#define yyset_lineno S1_set_lineno
#endif

#ifdef yywrap
#define S1_wrap_ALREADY_DEFINED
#else
#define yywrap S1_wrap
#endif

#ifdef yyalloc
#define S1_alloc_ALREADY_DEFINED
#else
#define yyalloc S1_alloc
#endif

#ifdef yyrealloc
#define S1_realloc_ALREADY_DEFINED
#else
#define yyrealloc S1_realloc
#endif

#ifdef yyfree
#define S1_free_ALREADY_DEFINED
#else
#define yyfree S1_free
#endif

#ifdef yytext
#define S1_text_ALREADY_DEFINED
#else
#define yytext S1_text
#endif

#ifdef yyleng
#define S1_leng_ALREADY_DEFINED
#else
#define yyleng S1_leng
#endif

#ifdef yyin
#define S1_in_ALREADY_DEFINED
#else
#define yyin S1_in
#endif

#ifdef yyout
#define S1_out_ALREADY_DEFINED
#else
#define yyout S1_out
#endif

#ifdef yyflexdebug
#define S1_flexdebug_ALREADY_DEFINED
#else
#define yyflexdebug S1_flexdebug
#endif

#ifdef yylineno
#define S1_lineno_ALREADY_DEFINED
#else
#define yylineno S1_lineno
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */

/* Feature test macros. Flex uses functions that require a minimum set of
 * macros defined. As defining some macros may hide function declarations that
 * user code might use, be conservative and respect user's definitions as much
 * as possible. In glibc, feature test macros may not be all set up until one
 * of the libc header (that includes <features.h>) is included. This creates
 * a circular dependency when we check the macros. <assert.h> is the safest
 * header we can include and does not declare too many functions we don't need.
 */
#if !defined(__GNU_LIBRARY__) && defined(__STDC__)
#include <assert.h>
#endif
#if !(defined(_POSIX_C_SOURCE) || defined(_XOPEN_SOURCE) || \
    defined(_POSIX_SOURCE))
# define _POSIX_C_SOURCE 1 /* Required for fileno() */
# define _POSIX_SOURCE 1
#endif
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* begin standard C++ headers. */

/* flex integer type definitions */

#ifndef YYFLEX_INTTYPES_DEFINED
#define YYFLEX_INTTYPES_DEFINED

/* Prefer C99 integer types if available. */

# if defined(__cplusplus) && __cplusplus >= 201103L
#include <cstdint>
#  define YYFLEX_USE_STDINT
# endif
# if defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L
/* Include <inttypes.h> and not <stdint.h> because Solaris 2.6 has the former
 * and not the latter.
 */
#include <inttypes.h>
#  define YYFLEX_USE_STDINT
# else
#  if defined(_MSC_VER) && _MSC_VER >= 1600
/* Visual C++ 2010 does not define __STDC_VERSION__ and has <stdint.h> but not
 * <inttypes.h>.
 */
#include <stdint.h>
#   define YYFLEX_USE_STDINT
#  endif
# endif
# ifdef YYFLEX_USE_STDINT
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
# else
typedef unsigned char flex_uint8_t;
typedef short int flex_int16_t;
typedef unsigned short int flex_uint16_t;
#  ifdef __STDC__
typedef signed char flex_int8_t;
/* ISO C only requires at least 16 bits for int. */
#   ifdef __cplusplus
#include <climits>
#   else
#include <limits.h>
#   endif
#   if UINT_MAX >= 4294967295
#    define YYFLEX_INT32_DEFINED
typedef int flex_int32_t;
typedef unsigned int flex_uint32_t;
#   endif
#  else
typedef char flex_int8_t;
#  endif
#  ifndef YYFLEX_INT32_DEFINED
typedef long int flex_int32_t;
typedef unsigned long int flex_uint32_t;
#  endif
# endif
#endif /* YYFLEX_INTTYPES_DEFINED */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define yybegin(s) (yy_start) = 1 + 2 * (s)
/* Legacy interface */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define yystart() (((yy_start) - 1) / 2)
/* Legacy interfaces */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* The state buf must be large enough to hold one state per character in the main buffer,
 * plus the start state, plus the two end-of-buffer byte states.
 */
#define YY_STATE_BUF_EXTRA_SPACE 3
#define YY_STATE_BUF_SIZE   (YY_BUF_SIZE + YY_STATE_BUF_EXTRA_SPACE)

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *yybuffer;
/* Legacy interface */
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define yyunput(c) yyunput_r( c, (yytext_ptr)  )
/* Legacy interface */
#define unput(c) yyunput_r( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{

	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yyatbol;

	int yy_bs_lineno; /**< The line count. */
	int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static yybuffer * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define yy_current_buffer() ( (yy_buffer_stack)			\
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Legacy interface */
#define YY_CURRENT_BUFFER yy_current_buffer()
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( yybuffer new_buffer  );
yybuffer yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( yybuffer b  );
void yy_flush_buffer ( yybuffer b  );
void yypush_buffer_state ( yybuffer new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( yybuffer b, FILE *file  );
#define yy_flush_current_buffer() yy_flush_buffer( yy_current_buffer() )
#define YY_FLUSH_BUFFER yy_flush_current_buffer()

yybuffer yy_scan_buffer ( char *base, yy_size_t size  );
yybuffer yy_scan_string ( const char *yy_str  );
yybuffer yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) { \
	if ( yy_current_buffer() == NULL ) { \
		yyensure_buffer_stack ();	\
		YY_CURRENT_BUFFER_LVALUE =    \
			yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
}
#define yysetbol(at_bol) \
	{ \
	if ( yy_current_buffer() == NULL ) { \
		yyensure_buffer_stack ();	\
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yyatbol = at_bol; \
}
#define yyatbol() (YY_CURRENT_BUFFER_LVALUE->yyatbol)
/* Legacy interface */
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yyatbol)
#define yy_set_bol(at_bol) \
	{ \
	if ( yy_current_buffer() == NULL ) { \
		yyensure_buffer_stack ();	\
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yyatbol = at_bol; \
}

/* Begin user sect3 */

#define S1_wrap() (/*CONSTCOND*/1)

#define YY_SKIP_YYWRAP

typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef const struct yy_trans_info *yy_state_type;

extern int yylineno;
int yylineno = 1;

/* Watch out: yytext_ptr is a variable when yytext is an array,
 * but it's a macro when yytext is a pointer.
 */

extern char *yytext;

#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

/* %% [1.5] DFA */
/* START of m4 controls */
/* M4_MODE_NO_NULTRANS */
/* M4_MODE_NO_NULTRANS_FULLTBL */
/* M4_MODE_NULTRANS_FULLSPD */
/* END of m4 controls */

/* START of Flex-generated definitions */
#define YY_NUM_RULES 12
#define YY_END_OF_BUFFER 13
#define YY_JAMBASE 0
#define YY_JAMSTATE 0
#define YY_NUL_EC 256
#define YY_OFFSET_TYPE flex_int32_t
/* END of Flex-generated definitions */

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yypanic ( const char* msg  );

struct yy_trans_info
	{
	/* We require that yy_verify and yy_nxt must be of the same size int. */

	YY_OFFSET_TYPE yy_verify;

	/* In cases where its sister yy_verify *is* a "yes, there is
	 * a transition", yy_nxt is the offset (in records) to the
	 * next state.  In most cases where there is no transition,
	 * the value of yy_nxt is irrelevant.  If yy_nxt is the -1th
	 * record of a state, though, then yy_nxt is the action number
	 * for that state.
	 */
	 YY_OFFSET_TYPE yy_nxt;

	};

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	 \
	yyleng = (int) (yy_cp - yy_bp); \
	 \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
 \
	(yy_c_buf_p) = yy_cp;

extern int yyflexdebug;
int yyflexdebug = 0;
/* Legacy interface */
#ifndef yy_flex_debug
#define yy_flex_debug yyflexdebug
#endif

/* %% [2.0] data tables for the DFA are inserted here */

/* footprint: 17008 bytes */

/* m4 controls begin */
/* M4_MODE_HAS_BACKING_UP */
/* M4_MODE_NEED_YY_CP */
/* M4_MODE_NULTRANS_WRAP */
/* m4 controls end */

/* The transition table */
static const struct yy_trans_info yy_transition[2119] = {
{   0,   0},
{   0,1863},
{   0,   0},
{   0,1861},
{   1,1548},

{   2,1548},
{   3,1548},
{   4,1548},
{   5,1548},
{   6,1548},

{   7,1548},
{   8,1548},
{   9,1548},
{  10,1550},
{  11,1548},

{  12,1548},
{  13,1548},
{  14,1548},
{  15,1548},
{  16,1548},

{  17,1548},
{  18,1548},
{  19,1548},
{  20,1548},
{  21,1548},

{  22,1548},
{  23,1548},
{  24,1548},
{  25,1548},
{  26,1548},

{  27,1548},
{  28,1548},
{  29,1548},
{  30,1548},
{  31,1548},

{  32,1548},
{  33,1548},
{  34,1548},
{  35,1548},
{  36,1548},

{  37,1548},
{  38,1548},
{  39,1548},
{  40,1548},
{  41,1548},

{  42,1548},
{  43,1548},
{  44,1548},
{  45,1548},
{  46,1548},

{  47,1548},
{  48,1548},
{  49,1548},
{  50,1548},
{  51,1548},

{  52,1548},
{  53,1548},
{  54,1548},
{  55,1548},
{  56,1548},

{  57,1548},
{  58,1548},
{  59,1548},
{  60,1548},
{  61,1548},

{  62,1548},
{  63,1548},
{  64,1548},
{  65,1548},
{  66,1548},

{  67,1548},
{  68,1548},
{  69,1548},
{  70,1548},
{  71,1548},

{  72,1548},
{  73,1548},
{  74,1548},
{  75,1548},
{  76,1548},

{  77,1548},
{  78,1548},
{  79,1548},
{  80,1548},
{  81,1548},

{  82,1548},
{  83,1548},
{  84,1548},
{  85,1548},
{  86,1548},

{  87,1548},
{  88,1548},
{  89,1548},
{  90,1548},
{  91,1548},

{  92,1552},
{  93,1548},
{  94,1548},
{  95,1548},
{  96,1548},

{  97,1548},
{  98,1548},
{  99,1548},
{ 100,1548},
{ 101,1548},

{ 102,1548},
{ 103,1548},
{ 104,1548},
{ 105,1548},
{ 106,1548},

{ 107,1548},
{ 108,1548},
{ 109,1548},
{ 110,1548},
{ 111,1548},

{ 112,1548},
{ 113,1548},
{ 114,1548},
{ 115,1548},
{ 116,1548},

{ 117,1548},
{ 118,1548},
{ 119,1548},
{ 120,1548},
{ 121,1548},

{ 122,1548},
{ 123,1548},
{ 124,1548},
{ 125,1548},
{ 126,1548},

{ 127,1548},
{ 128,1548},
{ 129,1548},
{ 130,1548},
{ 131,1548},

{ 132,1548},
{ 133,1548},
{ 134,1548},
{ 135,1548},
{ 136,1548},

{ 137,1548},
{ 138,1548},
{ 139,1548},
{ 140,1548},
{ 141,1548},

{ 142,1548},
{ 143,1548},
{ 144,1548},
{ 145,1548},
{ 146,1548},

{ 147,1548},
{ 148,1548},
{ 149,1548},
{ 150,1548},
{ 151,1548},

{ 152,1548},
{ 153,1548},
{ 154,1548},
{ 155,1548},
{ 156,1548},

{ 157,1548},
{ 158,1548},
{ 159,1548},
{ 160,1548},
{ 161,1548},

{ 162,1548},
{ 163,1548},
{ 164,1548},
{ 165,1548},
{ 166,1548},

{ 167,1548},
{ 168,1548},
{ 169,1548},
{ 170,1548},
{ 171,1548},

{ 172,1548},
{ 173,1548},
{ 174,1548},
{ 175,1548},
{ 176,1548},

{ 177,1548},
{ 178,1548},
{ 179,1548},
{ 180,1548},
{ 181,1548},

{ 182,1548},
{ 183,1548},
{ 184,1548},
{ 185,1548},
{ 186,1548},

{ 187,1548},
{ 188,1548},
{ 189,1548},
{ 190,1548},
{ 191,1548},

{ 192,1548},
{ 193,1548},
{ 194,1548},
{ 195,1548},
{ 196,1548},

{ 197,1548},
{ 198,1548},
{ 199,1548},
{ 200,1548},
{ 201,1548},

{ 202,1548},
{ 203,1548},
{ 204,1548},
{ 205,1548},
{ 206,1548},

{ 207,1548},
{ 208,1548},
{ 209,1548},
{ 210,1548},
{ 211,1548},

{ 212,1548},
{ 213,1548},
{ 214,1548},
{ 215,1548},
{ 216,1548},

{ 217,1548},
{ 218,1548},
{ 219,1548},
{ 220,1548},
{ 221,1548},

{ 222,1548},
{ 223,1548},
{ 224,1548},
{ 225,1548},
{ 226,1548},

{ 227,1548},
{ 228,1548},
{ 229,1548},
{ 230,1548},
{ 231,1548},

{ 232,1548},
{ 233,1548},
{ 234,1548},
{ 235,1548},
{ 236,1548},

{ 237,1548},
{ 238,1548},
{ 239,1548},
{ 240,1548},
{ 241,1548},

{ 242,1548},
{ 243,1548},
{ 244,1548},
{ 245,1548},
{ 246,1548},

{ 247,1548},
{ 248,1548},
{ 249,1548},
{ 250,1548},
{ 251,1548},

{ 252,1548},
{ 253,1548},
{ 254,1548},
{ 255,1548},
{ 256,1548},

{   0,   0},
{   0,1603},
{   1,1290},
{   2,1290},
{   3,1290},

{   4,1290},
{   5,1290},
{   6,1290},
{   7,1290},
{   8,1290},

{   9,1290},
{  10,1292},
{  11,1290},
{  12,1290},
{  13,1290},

{  14,1290},
{  15,1290},
{  16,1290},
{  17,1290},
{  18,1290},

{  19,1290},
{  20,1290},
{  21,1290},
{  22,1290},
{  23,1290},

{  24,1290},
{  25,1290},
{  26,1290},
{  27,1290},
{  28,1290},

{  29,1290},
{  30,1290},
{  31,1290},
{  32,1290},
{  33,1290},

{  34,1290},
{  35,1290},
{  36,1290},
{  37,1290},
{  38,1290},

{  39,1290},
{  40,1290},
{  41,1290},
{  42,1290},
{  43,1290},

{  44,1290},
{  45,1290},
{  46,1290},
{  47,1290},
{  48,1290},

{  49,1290},
{  50,1290},
{  51,1290},
{  52,1290},
{  53,1290},

{  54,1290},
{  55,1290},
{  56,1290},
{  57,1290},
{  58,1290},

{  59,1290},
{  60,1290},
{  61,1290},
{  62,1290},
{  63,1290},

{  64,1290},
{  65,1290},
{  66,1290},
{  67,1290},
{  68,1290},

{  69,1290},
{  70,1290},
{  71,1290},
{  72,1290},
{  73,1290},

{  74,1290},
{  75,1290},
{  76,1290},
{  77,1290},
{  78,1290},

{  79,1290},
{  80,1290},
{  81,1290},
{  82,1290},
{  83,1290},

{  84,1290},
{  85,1290},
{  86,1290},
{  87,1290},
{  88,1290},

{  89,1290},
{  90,1290},
{  91,1290},
{  92,1294},
{  93,1290},

{  94,1290},
{  95,1290},
{  96,1290},
{  97,1290},
{  98,1290},

{  99,1290},
{ 100,1290},
{ 101,1290},
{ 102,1290},
{ 103,1290},

{ 104,1290},
{ 105,1290},
{ 106,1290},
{ 107,1290},
{ 108,1290},

{ 109,1290},
{ 110,1290},
{ 111,1290},
{ 112,1290},
{ 113,1290},

{ 114,1290},
{ 115,1290},
{ 116,1290},
{ 117,1290},
{ 118,1290},

{ 119,1290},
{ 120,1290},
{ 121,1290},
{ 122,1290},
{ 123,1290},

{ 124,1290},
{ 125,1290},
{ 126,1290},
{ 127,1290},
{ 128,1290},

{ 129,1290},
{ 130,1290},
{ 131,1290},
{ 132,1290},
{ 133,1290},

{ 134,1290},
{ 135,1290},
{ 136,1290},
{ 137,1290},
{ 138,1290},

{ 139,1290},
{ 140,1290},
{ 141,1290},
{ 142,1290},
{ 143,1290},

{ 144,1290},
{ 145,1290},
{ 146,1290},
{ 147,1290},
{ 148,1290},

{ 149,1290},
{ 150,1290},
{ 151,1290},
{ 152,1290},
{ 153,1290},

{ 154,1290},
{ 155,1290},
{ 156,1290},
{ 157,1290},
{ 158,1290},

{ 159,1290},
{ 160,1290},
{ 161,1290},
{ 162,1290},
{ 163,1290},

{ 164,1290},
{ 165,1290},
{ 166,1290},
{ 167,1290},
{ 168,1290},

{ 169,1290},
{ 170,1290},
{ 171,1290},
{ 172,1290},
{ 173,1290},

{ 174,1290},
{ 175,1290},
{ 176,1290},
{ 177,1290},
{ 178,1290},

{ 179,1290},
{ 180,1290},
{ 181,1290},
{ 182,1290},
{ 183,1290},

{ 184,1290},
{ 185,1290},
{ 186,1290},
{ 187,1290},
{ 188,1290},

{ 189,1290},
{ 190,1290},
{ 191,1290},
{ 192,1290},
{ 193,1290},

{ 194,1290},
{ 195,1290},
{ 196,1290},
{ 197,1290},
{ 198,1290},

{ 199,1290},
{ 200,1290},
{ 201,1290},
{ 202,1290},
{ 203,1290},

{ 204,1290},
{ 205,1290},
{ 206,1290},
{ 207,1290},
{ 208,1290},

{ 209,1290},
{ 210,1290},
{ 211,1290},
{ 212,1290},
{ 213,1290},

{ 214,1290},
{ 215,1290},
{ 216,1290},
{ 217,1290},
{ 218,1290},

{ 219,1290},
{ 220,1290},
{ 221,1290},
{ 222,1290},
{ 223,1290},

{ 224,1290},
{ 225,1290},
{ 226,1290},
{ 227,1290},
{ 228,1290},

{ 229,1290},
{ 230,1290},
{ 231,1290},
{ 232,1290},
{ 233,1290},

{ 234,1290},
{ 235,1290},
{ 236,1290},
{ 237,1290},
{ 238,1290},

{ 239,1290},
{ 240,1290},
{ 241,1290},
{ 242,1290},
{ 243,1290},

{ 244,1290},
{ 245,1290},
{ 246,1290},
{ 247,1290},
{ 248,1290},

{ 249,1290},
{ 250,1290},
{ 251,1290},
{ 252,1290},
{ 253,1290},

{ 254,1290},
{ 255,1290},
{ 256,1290},
{   0,   0},
{   0,1345},

{   1,1038},
{   2,1038},
{   3,1038},
{   4,1038},
{   5,1038},

{   6,1038},
{   7,1038},
{   8,1038},
{   9,1038},
{  10,1040},

{  11,1038},
{  12,1038},
{  13,1038},
{  14,1038},
{  15,1038},

{  16,1038},
{  17,1038},
{  18,1038},
{  19,1038},
{  20,1038},

{  21,1038},
{  22,1038},
{  23,1038},
{  24,1038},
{  25,1038},

{  26,1038},
{  27,1038},
{  28,1038},
{  29,1038},
{  30,1038},

{  31,1038},
{  32,1038},
{  33,1038},
{  34,1038},
{  35,1038},

{  36,1038},
{  37,1038},
{  38,1038},
{  39,1042},
{  40,1038},

{  41,1038},
{  42,1038},
{  43,1038},
{  44,1038},
{  45,1038},

{  46,1038},
{  47,1038},
{  48,1038},
{  49,1038},
{  50,1038},

{  51,1038},
{  52,1038},
{  53,1038},
{  54,1038},
{  55,1038},

{  56,1038},
{  57,1038},
{  58,1038},
{  59,1038},
{  60,1038},

{  61,1038},
{  62,1038},
{  63,1038},
{  64,1038},
{  65,1038},

{  66,1038},
{  67,1038},
{  68,1038},
{  69,1038},
{  70,1038},

{  71,1038},
{  72,1038},
{  73,1038},
{  74,1038},
{  75,1038},

{  76,1038},
{  77,1038},
{  78,1038},
{  79,1038},
{  80,1038},

{  81,1038},
{  82,1038},
{  83,1038},
{  84,1038},
{  85,1038},

{  86,1038},
{  87,1038},
{  88,1038},
{  89,1038},
{  90,1038},

{  91,1038},
{  92,1038},
{  93,1038},
{  94,1038},
{  95,1038},

{  96,1038},
{  97,1038},
{  98,1038},
{  99,1038},
{ 100,1038},

{ 101,1038},
{ 102,1038},
{ 103,1038},
{ 104,1038},
{ 105,1038},

{ 106,1038},
{ 107,1038},
{ 108,1038},
{ 109,1038},
{ 110,1038},

{ 111,1038},
{ 112,1038},
{ 113,1038},
{ 114,1038},
{ 115,1038},

{ 116,1038},
{ 117,1038},
{ 118,1038},
{ 119,1038},
{ 120,1038},

{ 121,1038},
{ 122,1038},
{ 123,1044},
{ 124,1038},
{ 125,1046},

{ 126,1038},
{ 127,1038},
{ 128,1038},
{ 129,1038},
{ 130,1038},

{ 131,1038},
{ 132,1038},
{ 133,1038},
{ 134,1038},
{ 135,1038},

{ 136,1038},
{ 137,1038},
{ 138,1038},
{ 139,1038},
{ 140,1038},

{ 141,1038},
{ 142,1038},
{ 143,1038},
{ 144,1038},
{ 145,1038},

{ 146,1038},
{ 147,1038},
{ 148,1038},
{ 149,1038},
{ 150,1038},

{ 151,1038},
{ 152,1038},
{ 153,1038},
{ 154,1038},
{ 155,1038},

{ 156,1038},
{ 157,1038},
{ 158,1038},
{ 159,1038},
{ 160,1038},

{ 161,1038},
{ 162,1038},
{ 163,1038},
{ 164,1038},
{ 165,1038},

{ 166,1038},
{ 167,1038},
{ 168,1038},
{ 169,1038},
{ 170,1038},

{ 171,1038},
{ 172,1038},
{ 173,1038},
{ 174,1038},
{ 175,1038},

{ 176,1038},
{ 177,1038},
{ 178,1038},
{ 179,1038},
{ 180,1038},

{ 181,1038},
{ 182,1038},
{ 183,1038},
{ 184,1038},
{ 185,1038},

{ 186,1038},
{ 187,1038},
{ 188,1038},
{ 189,1038},
{ 190,1038},

{ 191,1038},
{ 192,1038},
{ 193,1038},
{ 194,1038},
{ 195,1038},

{ 196,1038},
{ 197,1038},
{ 198,1038},
{ 199,1038},
{ 200,1038},

{ 201,1038},
{ 202,1038},
{ 203,1038},
{ 204,1038},
{ 205,1038},

{ 206,1038},
{ 207,1038},
{ 208,1038},
{ 209,1038},
{ 210,1038},

{ 211,1038},
{ 212,1038},
{ 213,1038},
{ 214,1038},
{ 215,1038},

{ 216,1038},
{ 217,1038},
{ 218,1038},
{ 219,1038},
{ 220,1038},

{ 221,1038},
{ 222,1038},
{ 223,1038},
{ 224,1038},
{ 225,1038},

{ 226,1038},
{ 227,1038},
{ 228,1038},
{ 229,1038},
{ 230,1038},

{ 231,1038},
{ 232,1038},
{ 233,1038},
{ 234,1038},
{ 235,1038},

{ 236,1038},
{ 237,1038},
{ 238,1038},
{ 239,1038},
{ 240,1038},

{ 241,1038},
{ 242,1038},
{ 243,1038},
{ 244,1038},
{ 245,1038},

{ 246,1038},
{ 247,1038},
{ 248,1038},
{ 249,1038},
{ 250,1038},

{ 251,1038},
{ 252,1038},
{ 253,1038},
{ 254,1038},
{ 255,1038},

{ 256,1038},
{   0,   0},
{   0,1087},
{   1, 780},
{   2, 780},

{   3, 780},
{   4, 780},
{   5, 780},
{   6, 780},
{   7, 780},

{   8, 780},
{   9, 780},
{  10, 782},
{  11, 780},
{  12, 780},

{  13, 780},
{  14, 780},
{  15, 780},
{  16, 780},
{  17, 780},

{  18, 780},
{  19, 780},
{  20, 780},
{  21, 780},
{  22, 780},

{  23, 780},
{  24, 780},
{  25, 780},
{  26, 780},
{  27, 780},

{  28, 780},
{  29, 780},
{  30, 780},
{  31, 780},
{  32, 780},

{  33, 780},
{  34, 780},
{  35, 780},
{  36, 780},
{  37, 780},

{  38, 780},
{  39, 784},
{  40, 780},
{  41, 780},
{  42, 780},

{  43, 780},
{  44, 780},
{  45, 780},
{  46, 780},
{  47, 780},

{  48, 780},
{  49, 780},
{  50, 780},
{  51, 780},
{  52, 780},

{  53, 780},
{  54, 780},
{  55, 780},
{  56, 780},
{  57, 780},

{  58, 780},
{  59, 780},
{  60, 780},
{  61, 780},
{  62, 780},

{  63, 780},
{  64, 780},
{  65, 780},
{  66, 780},
{  67, 780},

{  68, 780},
{  69, 780},
{  70, 780},
{  71, 780},
{  72, 780},

{  73, 780},
{  74, 780},
{  75, 780},
{  76, 780},
{  77, 780},

{  78, 780},
{  79, 780},
{  80, 780},
{  81, 780},
{  82, 780},

{  83, 780},
{  84, 780},
{  85, 780},
{  86, 780},
{  87, 780},

{  88, 780},
{  89, 780},
{  90, 780},
{  91, 780},
{  92, 780},

{  93, 780},
{  94, 780},
{  95, 780},
{  96, 780},
{  97, 780},

{  98, 780},
{  99, 780},
{ 100, 780},
{ 101, 780},
{ 102, 780},

{ 103, 780},
{ 104, 780},
{ 105, 780},
{ 106, 780},
{ 107, 780},

{ 108, 780},
{ 109, 780},
{ 110, 780},
{ 111, 780},
{ 112, 780},

{ 113, 780},
{ 114, 780},
{ 115, 780},
{ 116, 780},
{ 117, 780},

{ 118, 780},
{ 119, 780},
{ 120, 780},
{ 121, 780},
{ 122, 780},

{ 123, 786},
{ 124, 780},
{ 125, 788},
{ 126, 780},
{ 127, 780},

{ 128, 780},
{ 129, 780},
{ 130, 780},
{ 131, 780},
{ 132, 780},

{ 133, 780},
{ 134, 780},
{ 135, 780},
{ 136, 780},
{ 137, 780},

{ 138, 780},
{ 139, 780},
{ 140, 780},
{ 141, 780},
{ 142, 780},

{ 143, 780},
{ 144, 780},
{ 145, 780},
{ 146, 780},
{ 147, 780},

{ 148, 780},
{ 149, 780},
{ 150, 780},
{ 151, 780},
{ 152, 780},

{ 153, 780},
{ 154, 780},
{ 155, 780},
{ 156, 780},
{ 157, 780},

{ 158, 780},
{ 159, 780},
{ 160, 780},
{ 161, 780},
{ 162, 780},

{ 163, 780},
{ 164, 780},
{ 165, 780},
{ 166, 780},
{ 167, 780},

{ 168, 780},
{ 169, 780},
{ 170, 780},
{ 171, 780},
{ 172, 780},

{ 173, 780},
{ 174, 780},
{ 175, 780},
{ 176, 780},
{ 177, 780},

{ 178, 780},
{ 179, 780},
{ 180, 780},
{ 181, 780},
{ 182, 780},

{ 183, 780},
{ 184, 780},
{ 185, 780},
{ 186, 780},
{ 187, 780},

{ 188, 780},
{ 189, 780},
{ 190, 780},
{ 191, 780},
{ 192, 780},

{ 193, 780},
{ 194, 780},
{ 195, 780},
{ 196, 780},
{ 197, 780},

{ 198, 780},
{ 199, 780},
{ 200, 780},
{ 201, 780},
{ 202, 780},

{ 203, 780},
{ 204, 780},
{ 205, 780},
{ 206, 780},
{ 207, 780},

{ 208, 780},
{ 209, 780},
{ 210, 780},
{ 211, 780},
{ 212, 780},

{ 213, 780},
{ 214, 780},
{ 215, 780},
{ 216, 780},
{ 217, 780},

{ 218, 780},
{ 219, 780},
{ 220, 780},
{ 221, 780},
{ 222, 780},

{ 223, 780},
{ 224, 780},
{ 225, 780},
{ 226, 780},
{ 227, 780},

{ 228, 780},
{ 229, 780},
{ 230, 780},
{ 231, 780},
{ 232, 780},

{ 233, 780},
{ 234, 780},
{ 235, 780},
{ 236, 780},
{ 237, 780},

{ 238, 780},
{ 239, 780},
{ 240, 780},
{ 241, 780},
{ 242, 780},

{ 243, 780},
{ 244, 780},
{ 245, 780},
{ 246, 780},
{ 247, 780},

{ 248, 780},
{ 249, 780},
{ 250, 780},
{ 251, 780},
{ 252, 780},

{ 253, 780},
{ 254, 780},
{ 255, 780},
{ 256, 780},
{   0,   0},

{   0, 829},
{   1, 532},
{   2, 532},
{   3, 532},
{   4, 532},

{   5, 532},
{   6, 532},
{   7, 532},
{   8, 532},
{   9, 532},

{  10, 524},
{  11, 532},
{  12, 532},
{  13, 532},
{  14, 532},

{  15, 532},
{  16, 532},
{  17, 532},
{  18, 532},
{  19, 532},

{  20, 532},
{  21, 532},
{  22, 532},
{  23, 532},
{  24, 532},

{  25, 532},
{  26, 532},
{  27, 532},
{  28, 532},
{  29, 532},

{  30, 532},
{  31, 532},
{  32, 532},
{  33, 532},
{  34, 532},

{  35, 532},
{  36, 532},
{  37, 532},
{  38, 532},
{  39, 534},

{  40, 532},
{  41, 532},
{  42, 532},
{  43, 532},
{  44, 532},

{  45, 532},
{  46, 532},
{  47, 532},
{  48, 532},
{  49, 532},

{  50, 532},
{  51, 532},
{  52, 532},
{  53, 532},
{  54, 532},

{  55, 532},
{  56, 532},
{  57, 532},
{  58, 532},
{  59, 532},

{  60, 532},
{  61, 532},
{  62, 532},
{  63, 532},
{  64, 532},

{  65, 532},
{  66, 532},
{  67, 532},
{  68, 532},
{  69, 532},

{  70, 532},
{  71, 532},
{  72, 532},
{  73, 532},
{  74, 532},

{  75, 532},
{  76, 532},
{  77, 532},
{  78, 532},
{  79, 532},

{  80, 532},
{  81, 532},
{  82, 532},
{  83, 532},
{  84, 532},

{  85, 532},
{  86, 532},
{  87, 532},
{  88, 532},
{  89, 532},

{  90, 532},
{  91, 532},
{  92, 532},
{  93, 532},
{  94, 532},

{  95, 532},
{  96, 532},
{  97, 532},
{  98, 532},
{  99, 532},

{ 100, 532},
{ 101, 532},
{ 102, 532},
{ 103, 532},
{ 104, 532},

{ 105, 532},
{ 106, 532},
{ 107, 532},
{ 108, 532},
{ 109, 532},

{ 110, 532},
{ 111, 532},
{ 112, 532},
{ 113, 532},
{ 114, 532},

{ 115, 532},
{ 116, 532},
{ 117, 532},
{ 118, 532},
{ 119, 532},

{ 120, 532},
{ 121, 532},
{ 122, 532},
{ 123, 538},
{ 124, 532},

{ 125, 540},
{ 126, 532},
{ 127, 532},
{ 128, 532},
{ 129, 532},

{ 130, 532},
{ 131, 532},
{ 132, 532},
{ 133, 532},
{ 134, 532},

{ 135, 532},
{ 136, 532},
{ 137, 532},
{ 138, 532},
{ 139, 532},

{ 140, 532},
{ 141, 532},
{ 142, 532},
{ 143, 532},
{ 144, 532},

{ 145, 532},
{ 146, 532},
{ 147, 532},
{ 148, 532},
{ 149, 532},

{ 150, 532},
{ 151, 532},
{ 152, 532},
{ 153, 532},
{ 154, 532},

{ 155, 532},
{ 156, 532},
{ 157, 532},
{ 158, 532},
{ 159, 532},

{ 160, 532},
{ 161, 532},
{ 162, 532},
{ 163, 532},
{ 164, 532},

{ 165, 532},
{ 166, 532},
{ 167, 532},
{ 168, 532},
{ 169, 532},

{ 170, 532},
{ 171, 532},
{ 172, 532},
{ 173, 532},
{ 174, 532},

{ 175, 532},
{ 176, 532},
{ 177, 532},
{ 178, 532},
{ 179, 532},

{ 180, 532},
{ 181, 532},
{ 182, 532},
{ 183, 532},
{ 184, 532},

{ 185, 532},
{ 186, 532},
{ 187, 532},
{ 188, 532},
{ 189, 532},

{ 190, 532},
{ 191, 532},
{ 192, 532},
{ 193, 532},
{ 194, 532},

{ 195, 532},
{ 196, 532},
{ 197, 532},
{ 198, 532},
{ 199, 532},

{ 200, 532},
{ 201, 532},
{ 202, 532},
{ 203, 532},
{ 204, 532},

{ 205, 532},
{ 206, 532},
{ 207, 532},
{ 208, 532},
{ 209, 532},

{ 210, 532},
{ 211, 532},
{ 212, 532},
{ 213, 532},
{ 214, 532},

{ 215, 532},
{ 216, 532},
{ 217, 532},
{ 218, 532},
{ 219, 532},

{ 220, 532},
{ 221, 532},
{ 222, 532},
{ 223, 532},
{ 224, 532},

{ 225, 532},
{ 226, 532},
{ 227, 532},
{ 228, 532},
{ 229, 532},

{ 230, 532},
{ 231, 532},
{ 232, 532},
{ 233, 532},
{ 234, 532},

{ 235, 532},
{ 236, 532},
{ 237, 532},
{ 238, 532},
{ 239, 532},

{ 240, 532},
{ 241, 532},
{ 242, 532},
{ 243, 532},
{ 244, 532},

{ 245, 532},
{ 246, 532},
{ 247, 532},
{ 248, 532},
{ 249, 532},

{ 250, 532},
{ 251, 532},
{ 252, 532},
{ 253, 532},
{ 254, 532},

{ 255, 532},
{ 256, 532},
{   0,   0},
{   0, 571},
{   1, 274},

{   2, 274},
{   3, 274},
{   4, 274},
{   5, 274},
{   6, 274},

{   7, 274},
{   8, 274},
{   9, 274},
{  10, 266},
{  11, 274},

{  12, 274},
{  13, 274},
{  14, 274},
{  15, 274},
{  16, 274},

{  17, 274},
{  18, 274},
{  19, 274},
{  20, 274},
{  21, 274},

{  22, 274},
{  23, 274},
{  24, 274},
{  25, 274},
{  26, 274},

{  27, 274},
{  28, 274},
{  29, 274},
{  30, 274},
{  31, 274},

{  32, 274},
{  33, 274},
{  34, 274},
{  35, 274},
{  36, 274},

{  37, 274},
{  38, 274},
{  39, 276},
{  40, 274},
{  41, 274},

{  42, 274},
{  43, 274},
{  44, 274},
{  45, 274},
{  46, 274},

{  47, 274},
{  48, 274},
{  49, 274},
{  50, 274},
{  51, 274},

{  52, 274},
{  53, 274},
{  54, 274},
{  55, 274},
{  56, 274},

{  57, 274},
{  58, 274},
{  59, 274},
{  60, 274},
{  61, 274},

{  62, 274},
{  63, 274},
{  64, 274},
{  65, 274},
{  66, 274},

{  67, 274},
{  68, 274},
{  69, 274},
{  70, 274},
{  71, 274},

{  72, 274},
{  73, 274},
{  74, 274},
{  75, 274},
{  76, 274},

{  77, 274},
{  78, 274},
{  79, 274},
{  80, 274},
{  81, 274},

{  82, 274},
{  83, 274},
{  84, 274},
{  85, 274},
{  86, 274},

{  87, 274},
{  88, 274},
{  89, 274},
{  90, 274},
{  91, 274},

{  92, 274},
{  93, 274},
{  94, 274},
{  95, 274},
{  96, 274},

{  97, 274},
{  98, 274},
{  99, 274},
{ 100, 274},
{ 101, 274},

{ 102, 274},
{ 103, 274},
{ 104, 274},
{ 105, 274},
{ 106, 274},

{ 107, 274},
{ 108, 274},
{ 109, 274},
{ 110, 274},
{ 111, 274},

{ 112, 274},
{ 113, 274},
{ 114, 274},
{ 115, 274},
{ 116, 274},

{ 117, 274},
{ 118, 274},
{ 119, 274},
{ 120, 274},
{ 121, 274},

{ 122, 274},
{ 123, 280},
{ 124, 274},
{ 125, 282},
{ 126, 274},

{ 127, 274},
{ 128, 274},
{ 129, 274},
{ 130, 274},
{ 131, 274},

{ 132, 274},
{ 133, 274},
{ 134, 274},
{ 135, 274},
{ 136, 274},

{ 137, 274},
{ 138, 274},
{ 139, 274},
{ 140, 274},
{ 141, 274},

{ 142, 274},
{ 143, 274},
{ 144, 274},
{ 145, 274},
{ 146, 274},

{ 147, 274},
{ 148, 274},
{ 149, 274},
{ 150, 274},
{ 151, 274},

{ 152, 274},
{ 153, 274},
{ 154, 274},
{ 155, 274},
{ 156, 274},

{ 157, 274},
{ 158, 274},
{ 159, 274},
{ 160, 274},
{ 161, 274},

{ 162, 274},
{ 163, 274},
{ 164, 274},
{ 165, 274},
{ 166, 274},

{ 167, 274},
{ 168, 274},
{ 169, 274},
{ 170, 274},
{ 171, 274},

{ 172, 274},
{ 173, 274},
{ 174, 274},
{ 175, 274},
{ 176, 274},

{ 177, 274},
{ 178, 274},
{ 179, 274},
{ 180, 274},
{ 181, 274},

{ 182, 274},
{ 183, 274},
{ 184, 274},
{ 185, 274},
{ 186, 274},

{ 187, 274},
{ 188, 274},
{ 189, 274},
{ 190, 274},
{ 191, 274},

{ 192, 274},
{ 193, 274},
{ 194, 274},
{ 195, 274},
{ 196, 274},

{ 197, 274},
{ 198, 274},
{ 199, 274},
{ 200, 274},
{ 201, 274},

{ 202, 274},
{ 203, 274},
{ 204, 274},
{ 205, 274},
{ 206, 274},

{ 207, 274},
{ 208, 274},
{ 209, 274},
{ 210, 274},
{ 211, 274},

{ 212, 274},
{ 213, 274},
{ 214, 274},
{ 215, 274},
{ 216, 274},

{ 217, 274},
{ 218, 274},
{ 219, 274},
{ 220, 274},
{ 221, 274},

{ 222, 274},
{ 223, 274},
{ 224, 274},
{ 225, 274},
{ 226, 274},

{ 227, 274},
{ 228, 274},
{ 229, 274},
{ 230, 274},
{ 231, 274},

{ 232, 274},
{ 233, 274},
{ 234, 274},
{ 235, 274},
{ 236, 274},

{ 237, 274},
{ 238, 274},
{ 239, 274},
{ 240, 274},
{ 241, 274},

{ 242, 274},
{ 243, 274},
{ 244, 274},
{ 245, 274},
{ 246, 274},

{ 247, 274},
{ 248, 274},
{ 249, 274},
{ 250, 274},
{ 251, 274},

{ 252, 274},
{ 253, 274},
{ 254, 274},
{ 255, 274},
{ 256, 274},

{   0,  10},
{   0, 313},
{   0,  11},
{   0, 311},
{   0,  10},

{   0, 309},
{   0,   5},
{   0, 307},
{   0,  12},
{   0, 305},

{   0,   5},
{   0, 303},
{   0,   2},
{   0, 301},
{   0,   3},

{   0, 299},
{   0,   9},
{   0, 297},
{   0,   9},
{   0, 295},

{   0,   0},
{  10,  22},
{   0,   6},
{   0, 291},
{   0,   7},

{   0, 289},
{   0,   0},
{   0, 287},
{   0,   0},
{  10,  16},

{   0,   0},
{   0, 283},
{   0,   0},
{   0, 281},
{   0,   0},

{   0, 279},
{   0,   0},
{   0, 277},
{   0,   0},
{   0, 275},

{   0,   4},
{   0, 273},
{   0,   8},
{   0, 271},
{   0,   0},

{   0, 269},
{   0,   0},
{   0,   0},
{   0, 266},
{   0,   0},

{   0, 264},
{   0,   0},
{   0, 262},
{   0,   1},
{   0, 260},

{   0,   0},
{   0, 258},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{  39,   8},
{   0,   0},
{  39,   8},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{ 102,  22},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{ 116,  26},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{ 102,   8},
{  97,   8},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{ 114,  10},
{   0,   0},
{   0,   0},
{  99,   5},

{  97,   4},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{  99,   4},
{   0,   0},
{ 114,   9},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{ 123,   4},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{ 123,  -2},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{ 257,  13},
{   1,   0},

};

/* Table of pointers to start states. */
static const struct yy_trans_info *yy_start_state_list[7] = {
	&yy_transition[1],
	&yy_transition[3],
	&yy_transition[261],
	&yy_transition[519],
	&yy_transition[777],
	&yy_transition[1035],
	&yy_transition[1293],
};

/* Definitions for backing up.  We don't need them if yyreject()
 * is being used because then we use an alternative backing-up
 * technique instead.
 */
static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of yyreject() which flex missed.
 */
#define yyreject() reject_used_but_not_detected
#define REJECT reject_used_but_not_detected

#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET

char *yytext;

/* %% [3.0] static declarations conditional on mode switches go here */
#line 1 "scanner.l"
#line 2 "scanner.l"
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
int balanced;
char numerator[4096];
char denominator[4096];
char output[8192];
char filename[256];
char results_filename[256];




#define INITIAL 0
#define NUMERATOR 1
#define DENOMINATOR 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */

#include <unistd.h>

#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_YYUNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#define YY_NO_YYINPUT 1

#ifndef YY_NO_YYINPUT

static int yyinput ( void );
#ifndef __cplusplus
#define input yyinput
#endif

#endif

        static int yy_start_stack_ptr = 0;
        static int yy_start_stack_depth = 0;
        static int *yy_start_stack = NULL;
    
    static void yy_push_state ( int _new_state );
    
    static void yy_pop_state ( void );
    
/*
 * Amount of stuff to slurp up with each read.
 * We assume the stdio library has already
 * chosen a fit size foe whatever platform
 * we're running on.
 */
#define YY_READ_BUF_SIZE BUFSIZ

/* Size of default input buffer. We want to be able to fit two
 * OS-level reads, but efficiency gains as the buffer size
 * increases fall off after that
 */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE	(2 * YY_READ_BUF_SIZE)
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef yyecho

/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define yyecho() do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)

#endif
/* Legacy interface */
#define ECHO yyecho()

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yypanic (const char* msg ) {
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Report a fatal error. Legacy interface. */
#ifndef YY_FATAL_ERROR

#define YY_FATAL_ERROR(msg) yypanic( msg )

#endif

/* Legacy interface */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) do {result = yyread(buf, max_size );} while (0)

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */

static int yyread(char *buf, size_t max_size ) {

	int result;
	
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) {
		int c = '*';
		int n;
		for ( n = 0; n < max_size &&
			      (c = getc( yyin )) != EOF && c != '\n'; ++n ) {
			buf[n] = (char) c;
		}
		if ( c == '\n' ) {
			buf[n++] = (char) c;
		}
		if ( c == EOF && ferror( yyin ) ) {
			YY_FATAL_ERROR( "input in flex scanner failed" );
		}
		result = n;
	} else {
		errno=0;
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) {
			if( errno != EINTR) {
				YY_FATAL_ERROR( "input in flex scanner failed" );
				break;
			}
			errno=0;
			clearerr(yyin);
		}
	}

	 return result;
}
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)

#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

#define YY_RULE_SETUP \
		YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL {
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) ) {
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) ) {
			(yy_start) = 1;	/* first start state */
		}
		if ( ! yyin ) {

			yyin = stdin;

		}
		if ( ! yyout ) {

			yyout = stdout;

		}
		if ( yy_current_buffer() == NULL ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
	}

	/* open scope of user declarationns */
	{
/* %% [4.0] user's declarations go here */
#line 21 "scanner.l"



		while ( /*CONSTCOND*/1 ) {		/* loops until end-of-file is reached */

			yy_cp = (yy_c_buf_p);

			/* Support of yytext. */
			*yy_cp = (yy_hold_char);

			/* yy_bp points to the position in yy_ch_buf of the start of
			 * the current run.
			 */
			yy_bp = yy_cp;

	/* Generate the code to find the start state. */

yy_current_state = yy_start_state_list[(yy_start)];

	yy_match:
			/* Generate the code to find the next match. */

		{
			const struct yy_trans_info *yy_trans_info;
			YY_CHAR yy_c;

			for ( yy_c = YY_SC_TO_UI(*yy_cp);
			      (yy_trans_info = &yy_current_state[yy_c])->yy_verify == yy_c;
			      yy_c = YY_SC_TO_UI(*++yy_cp) )
			{
				yy_current_state += yy_trans_info->yy_nxt;

		/* Generate code to keep backing-up information. */

		 if ( yy_current_state[-1].yy_nxt ) {

			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
		}

			}
		}

	yy_find_action:
			/* code to find the action number goes here */
			yy_act = yy_current_state[-1].yy_nxt;
			
			YY_DO_BEFORE_ACTION;

		do_action:	/* This label is used only to access EOF actions. */

			switch ( yy_act ) { /* beginning of action switch */

			case 0: /* must back up */
				/* undo the effects of YY_DO_BEFORE_ACTION */
				*yy_cp = (yy_hold_char);

				/* Backing-up info for compressed tables is taken \after/ */
				/* yy_cp has been incremented for the next state. */
				yy_cp = (yy_last_accepting_cpos);
				yy_cp++;
				
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;

/* %% [5.0] user actions get inserted here */
	case 1:
YY_RULE_SETUP

#line 22 "scanner.l"
{
			memset(numerator,'\0',4096);
			memset(denominator,'\0',4096); 
			memset(output,'\0',8192);
			strcpy(output,yytext);	
			balanced--;
			BEGIN(NUMERATOR); 
}
	/*LINTED*/break;
	case 2:
YY_RULE_SETUP

#line 30 "scanner.l"
{ 
			balanced--; 
			strcat(numerator,yytext);
} 
	/*LINTED*/break;
	case 3:
YY_RULE_SETUP

#line 34 "scanner.l"
{ 
			balanced++; 
			strcat(numerator,yytext);
			if(balanced==0){
				BEGIN(DENOMINATOR);	
			} else { 
				strcat(numerator,yytext);
			 }
		}
	/*LINTED*/break;
	case 4:
/* rule 4 can match eol */
YY_RULE_SETUP

#line 44 "scanner.l"
{
		strcat(numerator,yytext);
}
	/*LINTED*/break;
	case 5:
YY_RULE_SETUP

#line 48 "scanner.l"
{
		strcat(numerator,yytext);
 }
	/*LINTED*/break;
	case 6:
YY_RULE_SETUP

#line 52 "scanner.l"
{ 
		balanced--;  
		strcat(denominator,yytext);
}
	/*LINTED*/break;
	case 7:
YY_RULE_SETUP

#line 57 "scanner.l"
{ 
			balanced++; 
			strcat(denominator,yytext);
			if(balanced==0){
			fprintf(S1_out,"%s%s%s<T_SPLIT>%s\n",output,numerator,denominator,filename);
			BEGIN(0);	
	} else { 
		strcat(denominator,yytext);
}}
	/*LINTED*/break;
	case 8:
/* rule 8 can match eol */
YY_RULE_SETUP

#line 66 "scanner.l"
{  
		strcat(denominator,yytext);
}
	/*LINTED*/break;
	case 9:
YY_RULE_SETUP

#line 69 "scanner.l"
{ 
	strcat(denominator,yytext); 
}
	/*LINTED*/break;
	case 10:
YY_RULE_SETUP

#line 72 "scanner.l"
;
	/*LINTED*/break;
	case 11:
/* rule 11 can match eol */
YY_RULE_SETUP

#line 73 "scanner.l"
;
	/*LINTED*/break;
	case 12:
YY_RULE_SETUP

#line 74 "scanner.l"
yyecho();
	/*LINTED*/break;


	case YY_STATE_EOF(INITIAL):
		/* FALLTHROUGH */
	case YY_STATE_EOF(NUMERATOR):
		/* FALLTHROUGH */
	case YY_STATE_EOF(DENOMINATOR):
		/* FALLTHROUGH */
		yyterminate();

			case YY_END_OF_BUFFER:
			{
				/* Amount of text matched not including the EOB char. */
				int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

				/* Undo the effects of YY_DO_BEFORE_ACTION. */
				*yy_cp = (yy_hold_char);
				YY_RESTORE_YY_MORE_OFFSET

				if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW ) {
					/* We're scanning a new file or input source.  It's
					 * possible that this happened because the user
					 * just pointed yyin at a new source and called
					 * yylex().  If so, then we have to assure
					 * consistency between yy_current_buffer() and our
					 * globals.  Here is the right place to do so, because
					 * this is the first action (other than possibly a
					 * back-up) that will match for the new input source.
					 */
					(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;

					YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;

					YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
				}

				/* Note that here we test for yy_c_buf_p "<=" to the position
				 * of the first EOB in the buffer, since yy_c_buf_p will
				 * already have been incremented past the NUL character
				 * (since all states make transitions on EOB to the
				 * end-of-buffer state).  Contrast this with the test
				 * in input().
				 */
				if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] ) { /* This was really a NUL. */
					yy_state_type yy_next_state;

					(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

					yy_current_state = yy_get_previous_state(  );

					/* Okay, we're now positioned to make the NUL
					 * transition.  We couldn't have
					 * yy_get_previous_state() go ahead and do it
					 * for us because it doesn't know how to deal
					 * with the possibility of jamming (and we don't
					 * want to build jamming into it because then it
					 * will run more slowly).
					 */

					yy_next_state = yy_try_NUL_trans( yy_current_state );

					yy_bp = (yytext_ptr) + YY_MORE_ADJ;

					if ( yy_next_state ) {
						/* Consume the NUL. */
						yy_cp = ++(yy_c_buf_p);
						yy_current_state = yy_next_state;
						goto yy_match;
					} else {
						yy_cp = (yy_c_buf_p);
						
						goto yy_find_action;
					}
				} else {	/* not a NUL */
					switch ( yy_get_next_buffer(  ) ) {
					case EOB_ACT_END_OF_FILE:
						(yy_did_buffer_switch_on_eof) = 0;

						if ( yywrap(  ) ) {
							/* Note: because we've taken care in
							 * yy_get_next_buffer() to have set up
							 * yytext, we can now set up
							 * yy_c_buf_p so that if some total
							 * hoser (like flex itself) wants to
							 * call the scanner after we return the
							 * YY_NULL, it'll still work - another
							 * YY_NULL will get returned.
							 */
							(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

							yy_act = YY_STATE_EOF(yystart());
							goto do_action;
						} else {
							if ( ! (yy_did_buffer_switch_on_eof) ) {
								YY_NEW_FILE;
							}
						}
						break;
					case EOB_ACT_CONTINUE_SCAN:
						(yy_c_buf_p) =
							(yytext_ptr) + yy_amount_of_matched_text;

						yy_current_state = yy_get_previous_state(  );

						yy_cp = (yy_c_buf_p);
						yy_bp = (yytext_ptr) + YY_MORE_ADJ;
						goto yy_match;

					case EOB_ACT_LAST_MATCH:
						(yy_c_buf_p) =
						&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

						yy_current_state = yy_get_previous_state(  );

						yy_cp = (yy_c_buf_p);
						yy_bp = (yytext_ptr) + YY_MORE_ADJ;
						goto yy_find_action;
					} /* end EOB inner switch */
				} /* end if */
				break;
			} /* case YY_END_OF_BUFFER */
			default:
				YY_FATAL_ERROR("fatal flex scanner internal error--no action found" );
			} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer (void)

{
		char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] ) {
		YY_FATAL_ERROR( "fatal flex scanner internal error--end of buffer missed" );
	}
	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 ) {
		/* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 ) {
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
		} else {
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
		}
	}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i ) {
		*(dest++) = *(source++);
	}
	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING ) {
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;
	} else {
		int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 ) { /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			yybuffer b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer ) {
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 ) {
					b->yy_buf_size += b->yy_buf_size / 8;
				} else {
					b->yy_buf_size *= 2;
				}
				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
			} else {
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;
			}
			if ( ! b->yy_ch_buf ) {
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );
			}
			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

		}

		if ( num_to_read > YY_READ_BUF_SIZE ) {
			num_to_read = YY_READ_BUF_SIZE;
		}
		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
	}

	if ( (yy_n_chars) == 0 ) {
		if ( number_to_move == YY_MORE_ADJ ) {
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
		} else {
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
		}
	} else {
		ret_val = EOB_ACT_CONTINUE_SCAN;
	}
	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf ) {
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		}
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state (void)

{
	yy_state_type yy_current_state;
	char *yy_cp;
	
	/* Generate the code to find the start state. */

yy_current_state = yy_start_state_list[(yy_start)];

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp ) {
		/* Generate the code to find the next state. */
		
		yy_current_state += yy_current_state[(*yy_cp ? YY_SC_TO_UI(*yy_cp) : YY_NUL_EC)].yy_nxt;
		
		/* Generate code to keep backing-up information. */

		 if ( yy_current_state[-1].yy_nxt ) {

			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
		}

	}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )

{
	int yy_is_jam;
		/* Generate code for handling NUL's, if needed. */

	/* First, deal with backing up and setting up yy_cp if the scanner
	 * finds that it should JAM on the NUL.
	 *
	 * Only generate a definition for "yy_cp" if we'll generate code
	 * that uses it.  Otherwise lint and the like complain.
	 */
	char *yy_cp = (yy_c_buf_p);

	int yy_c = YY_NUL_EC;

	const struct yy_trans_info *yy_trans_info;

	yy_trans_info = &yy_current_state[(unsigned int) yy_c];
	yy_current_state += yy_trans_info->yy_nxt;
	yy_is_jam = (yy_trans_info->yy_verify != yy_c);

	/* If we've entered an accepting state, back up; note that
	 * compressed tables have *already* done such backing up, so
	 * we needn't bother with it again.
	 */
	if ( ! yy_is_jam ) {
		
		/* Generate code to keep backing-up information. */

		 if ( yy_current_state[-1].yy_nxt ) {

			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
		}

	}

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_YYINPUT
int yyinput (void)

{
	int c;
	
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR ) {
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] ) {
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';
		} else {
			/* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) ) {
			case EOB_ACT_LAST_MATCH:
				/* This happens because yy_g_n_b()
				 * sees that we've accumulated a
				 * token and flags that we need to
				 * try matching the token before
				 * proceeding.  But for input(),
				 * there's no matching to consider.
				 * So convert the EOB_ACT_LAST_MATCH
				 * to EOB_ACT_END_OF_FILE.
				 */

				/* Reset buffer status. */
				yyrestart( yyin );

				/*FALLTHROUGH*/

			case EOB_ACT_END_OF_FILE:
				if ( yywrap(  ) ) {
					return 0;
				}
				if ( ! (yy_did_buffer_switch_on_eof) ) {
					YY_NEW_FILE;
				}
				return yyinput();

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) = (yytext_ptr) + offset;
				break;
			}
		}
	}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}

#endif	/* ifndef YY_NO_YYINPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */

void yyrestart  (FILE * input_file )

{
		size_t new_size = 0;
	yy_state_type *new_state_buf = 0;

	if ( yy_current_buffer() == NULL ) {
		yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
	        	yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER_LVALUE, input_file );
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */

void yy_switch_to_buffer  (yybuffer  new_buffer )

{
		size_t new_size = 0;
	yy_state_type *new_state_buf = 0;

	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
	 */
	yyensure_buffer_stack ();
	if ( yy_current_buffer() == new_buffer ) {
		return;
	}
	if ( yy_current_buffer() ) {
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
	}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)

{
		(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;

	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;

	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */

yybuffer yy_create_buffer  (FILE * file, int  size )

{
	yybuffer b;
	
	b = (yybuffer) yyalloc( sizeof( struct yy_buffer_state )  );
	if (  b == NULL ) {
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );
	}
	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( b->yy_ch_buf == NULL ) {
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );
	}
	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */

void yy_delete_buffer (yybuffer  b )

{
	
	if ( b == NULL ) {
		return;
	}
	if ( b == yy_current_buffer() ) {	/* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (yybuffer) 0;
	}
	if ( b->yy_is_our_buffer ) {
		yyfree( (void *) b->yy_ch_buf  );
	}
	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */

static void yy_init_buffer  (yybuffer  b, FILE * file )

{
	int oerrno = errno;
	
	yy_flush_buffer( b );

	b->yy_input_file = file;

    /* b->yy_input_file should never by NULL but we'll handle it cleanly
	 * on the off chance.
	 */
	if (b->yy_input_file == NULL){
	  b->yy_fill_buffer = 0;
	} else {
	  b->yy_fill_buffer = 1;
	}

	/* If b is the current buffer, then yy_init_buffer was _probably_
	 * called from yyrestart() or through yy_get_next_buffer.
	 * In that case, we don't want to reset the lineno or column.
	 */
	if (b != yy_current_buffer()) {
		b->yy_bs_lineno = 1;
		b->yy_bs_column = 0;
	}

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c yy_current_buffer().
 * 
 */

void yy_flush_buffer (yybuffer  b )

{
		if ( b == NULL ) {
		return;
	}
	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yyatbol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer() ) {
		yy_load_buffer_state(  );
	}
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */

void yypush_buffer_state (yybuffer new_buffer )

{
		if (new_buffer == NULL) {
		return;
	}
	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( yy_current_buffer() != NULL ) {
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
	}

	/* Only push if top exists. Otherwise, replace top. */
	if (yy_current_buffer()) {
		(yy_buffer_stack_top)++;
	}
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */

void yypop_buffer_state (void)

{
		if (yy_current_buffer() == NULL) {
		return;
	}
	yy_delete_buffer(yy_current_buffer() );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0) {
		--(yy_buffer_stack_top);
	}
	if (yy_current_buffer() != NULL) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */

static void yyensure_buffer_stack (void)

{
	yy_size_t num_to_alloc;
	
	if ((yy_buffer_stack) == NULL) {
		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
		 */
		num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( (yy_buffer_stack == NULL) ) {
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
		}

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1) {
		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ((yy_buffer_stack) == NULL) {
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
		}
		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
yybuffer yy_scan_buffer  (char * base, yy_size_t  size )
{
	yybuffer b;
	
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR ) {
		/* They forgot to leave room for the EOB's. */
		return NULL;
	}
	b = (yybuffer) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( b == NULL ) {
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );
	}
	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yyatbol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
yybuffer yy_scan_string (const char * yystr )
{
	
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
yybuffer yy_scan_bytes  (const char * yybytes, int  _yybytes_len ) {
	yybuffer b;
	char *buf;
	yy_size_t n;
	int i;
	
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( buf == 0 ) {
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );
	}
	for ( i = 0; i < _yybytes_len; ++i ) {
		buf[i] = yybytes[i];
	}
	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( b == NULL ) {
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );
	}
	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

static void yy_push_state (int  _new_state )

{
		if ( (yy_start_stack_ptr) >= (yy_start_stack_depth) ) {
		yy_size_t new_size;

		(yy_start_stack_depth) += YY_START_STACK_INCR;
		new_size = (yy_size_t) (yy_start_stack_depth) * sizeof( int );

		if ( ! (yy_start_stack) ) {
			(yy_start_stack) = (int *) yyalloc( new_size  );

		} else {
			(yy_start_stack) = (int *) yyrealloc(
					(void *) (yy_start_stack), new_size  );
		}
		if ( ! (yy_start_stack) ) {
			YY_FATAL_ERROR( "out of memory expanding start-condition stack" );
		}
	}
	(yy_start_stack)[(yy_start_stack_ptr)++] = yystart();

	yybegin(_new_state);
}

static void yy_pop_state  (void)

{
		if ( --(yy_start_stack_ptr) < 0 ) {
		YY_FATAL_ERROR( "start-condition stack underflow" );
	}
	yybegin((yy_start_stack)[(yy_start_stack_ptr)]);
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do { \
		/* Undo effects of setting up yytext. */ \
		int yyless_macro_arg = (n); \
		YY_LESS_LINENO(yyless_macro_arg);\
			yytext[yyleng] = (yy_hold_char); \
			(yy_c_buf_p) = yytext + yyless_macro_arg; \
			(yy_hold_char) = *(yy_c_buf_p); \
			*(yy_c_buf_p) = '\0'; \
			yyleng = yyless_macro_arg; \
	} while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void) {
	
	return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void) {
		return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void) {
		return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void) {
		return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void) {
		return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number ) {
	
	yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str ) {
		yyin = _in_str ;
}

void yyset_out (FILE *  _out_str ) {
		yyout = _out_str ;
}

int yyget_debug  (void) {
		return yyflexdebug;
}

void yyset_debug (int  _bdebug ) {
		yyflexdebug = _bdebug ;
}

static int yy_init_globals (void) {
		/* Initialization is the same as for the non-reentrant scanner.
	 * This function is called from yylex_destroy(), so don't allocate here.
	 */

	(yy_buffer_stack) = NULL;
	(yy_buffer_stack_top) = 0;
	(yy_buffer_stack_max) = 0;
	(yy_c_buf_p) = NULL;
	(yy_init) = 0;
	(yy_start) = 0;

	(yy_start_stack_ptr) = 0;
	(yy_start_stack_depth) = 0;
	(yy_start_stack) =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
	yyin = stdin;
	yyout = stdout;
#else
	yyin = NULL;
	yyout = NULL;
#endif

	/* For future reference: Set errno on error, since we are called by
	 * yylex_init()
	 */
	return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void) {
	
	/* Pop the buffer stack, destroying each element. */
	while(yy_current_buffer()) {
		yy_delete_buffer( yy_current_buffer()  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

	/* Destroy the start condition stack. */
        yyfree( (yy_start_stack)  );
        (yy_start_stack) = NULL;

	/* Reset the globals. This is important in a non-reentrant scanner so the next time
	 * yylex() is called, initialization will occur. */
	yy_init_globals( );

	return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n ) {
		
	int i;
	for ( i = 0; i < n; ++i ) {
		s1[i] = s2[i];
	}
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size ) {
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size ) {
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr ) {
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#line 74 "scanner.l"



