
create schema api;
alter schema api owner to latexinarxiv;
create role web_anon nologin;
grant usage on schema api to web_anon;
create role authenticator noinherit login password 'mysecretpassword';
grant web_anon to authenticator;

create table abstract (filename text, abstract text, len bigint );
create table affiliation (filename text, affiliation text, len bigint );
create table aligned (filename text, aligned text, len bigint );
create table align (filename text, align text, len bigint );
create table author (filename text, author text, len bigint );
create table cases (filename text, cases text, len bigint );
create table cite (filename text, cite text, len bigint );
create table comments (filename text, comments text, len bigint );
create table description (filename text, description text, len bigint );
create table displaymath (filename text, displaymath text, len bigint );
create table emph (filename text, emph text, len bigint );
create table enumerate (filename text, enumerate text, len bigint );
create table flushleft (filename text, flushleft text, len bigint );
create table flushright (filename text, flushright text, len bigint );
create table fmfgraph (filename text, fmfgraph text, len bigint );
create table gather (filename text, gather text, len bigint );
create table label (filename text, label text, len bigint );
create table lemma (filename text, lemma text, len bigint );
create table list (filename text, list text, len bigint );
create table lstcode (filename text, lstcode text, len bigint );
create table lstlisting (filename text, lstlisting text, len bigint );
create table mathletters (filename text, mathletters text, len bigint );
create table matrix (filename text, matrix text, len bigint );
create table minipage (filename text, minipage text, len bigint );
create table minted (filename text, minted text, len bigint );
create table multline (filename text, multline text, len bigint );
create table params (filename text, params text, len bigint );
create table picture (filename text, picture text, len bigint );
create table pmatrix (filename text, pmatrix text, len bigint );
create table proof (filename text, proof text, len bigint );
create table prop (filename text, prop text, len bigint );
create table proposition (filename text, proposition text, len bigint );
create table quotation (filename text, quotation text, len bigint );
create table quote (filename text, quote text, len bigint );
--create table references (filename text, references text, len bigint );
create table ref (filename text, ref text, len bigint );
create table results (filename text, results text, len bigint );
create table scope (filename text, scope text, len bigint );
create table scores (filename text, scores text, len bigint );
create table section (filename text, section text, len bigint );
create table slm (filename text, slm text, len bigint );
create table split (filename text, split text, len bigint );
create table subequations (filename text, subequations text, len bigint );
--create table table (filename text, table text, len bigint );
create table tabular (filename text, tabular text, len bigint );
create table theorem (filename text, theorem text, len bigint );
create table title (filename text, title text, len bigint );
create table titlepage (filename text, titlepage text, len bigint );
create table url (filename text, url text, len bigint );
create table verbatim (filename text, verbatim text, len bigint );

alter table abstract owner to latexinarxiv;
alter table affiliation owner to latexinarxiv;
alter table aligned owner to latexinarxiv;
alter table align owner to latexinarxiv;
alter table author owner to latexinarxiv;
alter table cases owner to latexinarxiv;
alter table cite owner to latexinarxiv;
alter table comments owner to latexinarxiv;
alter table description owner to latexinarxiv;
alter table displaymath owner to latexinarxiv;
alter table emph owner to latexinarxiv;
alter table enumerate owner to latexinarxiv;
alter table flushleft owner to latexinarxiv;
alter table flushright owner to latexinarxiv;
alter table fmfgraph owner to latexinarxiv;
alter table gather owner to latexinarxiv;
alter table label owner to latexinarxiv;
alter table lemma owner to latexinarxiv;
alter table list owner to latexinarxiv;
alter table lstcode owner to latexinarxiv;
alter table lstlisting owner to latexinarxiv;
alter table mathletters owner to latexinarxiv;
alter table matrix owner to latexinarxiv;
alter table minipage owner to latexinarxiv;
alter table minted owner to latexinarxiv;
alter table multline owner to latexinarxiv;
alter table params owner to latexinarxiv;
alter table picture owner to latexinarxiv;
alter table pmatrix owner to latexinarxiv;
alter table proof owner to latexinarxiv;
alter table proposition owner to latexinarxiv;
alter table prop owner to latexinarxiv;
alter table quotation owner to latexinarxiv;
alter table quote owner to latexinarxiv;
--alter table references owner to latexinarxiv;
alter table ref owner to latexinarxiv;
alter table results owner to latexinarxiv;
alter table scope owner to latexinarxiv;
alter table scores owner to latexinarxiv;
alter table section owner to latexinarxiv;
alter table slm owner to latexinarxiv;
alter table split owner to latexinarxiv;
alter table subequations owner to latexinarxiv;
--alter table table owner to latexinarxiv;
alter table tabular owner to latexinarxiv;
alter table theorem owner to latexinarxiv;
alter table title owner to latexinarxiv;
alter table titlepage owner to latexinarxiv;
alter table url owner to latexinarxiv;
alter table verbatim owner to latexinarxiv;
