host: 127.0.0.1
user: latexinarxiv
dbname: latexinarxiv
password: 3e9f91486fa99d2fe94b2494baf5f2effe0791b6b040394cef4fbe1cefcada29
port: 5432

label_max_len: 100
cite_max_len: 100
slm_max_len: 1000
mlm_max_len: 1000
section_max_len: 100000
section_multi_line: true 

subsection_max_len: 8000
subsection_multi_line: true 
